# Generated by Django 2.2.18 on 2021-11-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=5000)),
                ('image_url', models.CharField(max_length=500)),
                ('vote_count', models.IntegerField(default=0)),
            ],
        ),
    ]
